title: Ardia Fatma Sari # your name (or website title) here
logo: "/image/ardiapoto.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I'm undergraduate of Mathematic Student at Universitas Negeri Malang. I have a number of experience in organization.
 
  Now, i'm learning data analytics for support my skill.
  <a href="https://www.linkedin.com/in/ardia-fatma-sari-20483625b/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
